### ISSUE TITLE
Fatal error after installing the last release

### ISSUE THREAD

**Issue by KarloStekovic** [infinum/eightshift-boilerplate#199]
Hi, after installing and activating the new theme i'm getting this fatal error.
<img width="757" alt="Screenshot 2020-03-05 at 10 46 59" src="https://user-images.githubusercontent.com/53526985/75971864-ac97e400-5ed2-11ea-9ce3-3d196d9a661a.png">

## Current Behavior

After installation and activation of the new theme, there is a fatal error

## Expected Behavior

To run normally :)
## Steps to Reproduce (for bugs)

1. Install new theme (npx create-wp-project)
2. Add define( 'PNW_ENV', 'develop' ); and wp-config-project.php in wp-config.php
3. Activate theme in wp-admin

## Your Environment

* PHP version: 7.1.4
* Development environment: Flywheel
* Server type: Nginx 
* Operating System and version: macOS Catalina 10.15.3

**Comment by iruzevic** [comment]
can you try running `composer dump-autoload` in the theme root where composer.json is?

**Comment by KarloStekovic** [comment]
Yes i did and it's still the same error

**Comment by IvanGrginovInf** [comment]
We've just released an update recently and for a short while the installation was broken, could you please try installing the theme again? Setting up a new theme should fix things, please run it like so just to be sure `npx create-wp-project@1.0.5`. (this is the latest install script version at the time of writing this)

**Comment by KarloStekovic** [comment]
I did run the new installation (npx create-wp-project@1.0.5) and there is still the same error.

**Comment by IvanGrginovInf** [comment]
Please try the following (make sure you have your browser's cache disabled):
1. Delete `vendor` folder
2. `composer clearcache`
3. `composer install`

Also can you please let us know the following:

1. Do you have `profico-new-website/src/class-config.php` file? If so please paste it's contents.
2. Can you paste your theme's (the one last one you installed) `vendor/composer/autoload_static.php` file?

**Comment by iruzevic** [comment]
If you could zip that theme and put it here and we will debug it

**Comment by dingo-d** [comment]
From the error message, it looks like the class `Profico_New_Website\Core\Config` in the `get_service_classes()` method doesn't exist. Make sure all the classes defined in the `get_service_classes()` method exist.

**Comment by KarloStekovic** [comment]
I installed a theme again after composer clearcache and now its working.. weird but it works.. Thanks guys for help

**Comment by iruzevic** [comment]
Bet debugging ever :D
